modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/unders-battle-mod" #optional
credits="The Player, Forge, HarryTalks" #optional
authors="Underplayer97" #optional

[[mods]] #mandatory
modId="ubm" #mandatory
version="0.2.0" #mandatory
displayName="Under's Battle Mod" #mandatory
description='''
A mod which you can use overpowered items
'''

[[dependencies.ubm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.ubm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"